name: dailyCI
on:
  schedule:
#      Every day at 10AM and 10PM UTC
#     - cron: '00 10,22 * * *'
#      Every Monday at 1PM UTC (6AM PST)
    - cron: '0 13 * * 1'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly'}}
    strategy:
      matrix:
        version:
          - '1.6' # LTS
          - '1' # Current Stable
          - 'nightly' # Upcoming
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      # - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
